export const theme = {
    colors: {
        backgroundPrimary: '#1F1F1F',
        backgroundSecondary: '#141414',
        backgroundSecondaryHover: '#181818',
        backgroundTertiary: '#5F5F5F',
        gradientMainPrimary: '#3D54DD',
        gradientMainSecondary: '#BD00ED',
        gradientAlternatePrimary: '#FF6B00',
        gradientAlternateSecondary: 'rgba(193, 83, 3, 0.75)',
        title: '#ffffff',
        titleAlternate: '#FF6B00',
        paragraph: '#C0C0C0',

        blue: '#3D54DD',
        lightBlue: '#6379FA',
        write: '#ffffff',
        grey: '#121212',
    },
    media: {
        smallMobile: '(max-width: 600px)',
        mobile: '(min-width: 600px) and (max-width: 768px)',
        tablet: '(min-width: 768px) and (max-width: 992px)',
        smallDesktop: '(min-width: 992px) and (max-width: 1200px)',
        normalDesktop: '(min-width: 1200px) and (max-width: 1600px)',
        largeDesktop: '(min-width: 1600px)',
    },
    container: {
        large: '130rem',
        medium: '108rem',
        small: '87rem',
        tablet: '72rem',
        mobile: '56rem',
        smallMobile: '100%',
    },
};
