import type { Metadata } from "next";
import Homepage from "./home";

export const metadata: Metadata = {
  title: "Lucas Lino | Portfólio",
  description: "Generated by create next app",
};

export default function Home() {
  return <Homepage />;
}
