import type { Metadata } from 'next';
import Homepage from './home';
import { initializeFirebase } from '@/utils/firebase';
import { getDatabase, ref, get, onValue } from 'firebase/database';
import 'firebase/database';

export const metadata: Metadata = {
    title: 'Lucas Lino | Portfólio',
    description: 'Generated by create next app',
};

export const revalidate = 86400;

export async function getData() {
    initializeFirebase();
    const db = getDatabase();

    try {
        const descriptionsRef = ref(db, 'descriptions');
        const skillsRef = ref(db, 'skills');
        const projectsRef = ref(db, 'projects');
        const contactsRef = ref(db, 'contacts');
        const descriptions = await get(descriptionsRef);
        const skills = await get(skillsRef);
        const projects = await get(projectsRef);
        const contacts = await get(contactsRef);
        return {
            descriptions: descriptions.val(),
            skills: skills.val(),
            projects: projects.val(),
            contacts: contacts.val(),
        };
    } catch (error) {
        console.error('Error fetching data from Firebase:', error);
        return {
            descriptions: null,
            skills: null,
            projects: null,
            contacts: null,
        };
    }
}

export default async function Home() {
    const data = await getData();
    return <Homepage {...data} />;
}
